"""CloudSentry — the catalog of all 60 security checks (metadata only).

Each entry is a dict describing a check. The actual evaluation logic lives in
the provider check modules; this catalog drives INFO mode, the dashboard,
reporting, and compliance scoring.

Keys: id, name, provider, category, severity, description, risk,
      remediation, cis, owasp
"""

from __future__ import annotations

CHECKS: list[dict] = [

# ---------------- AWS: IAM (10) ----------------
{"id": "AWS-IAM-001", "name": "Root account MFA enabled", "provider": "aws", "category": "IAM",
 "severity": "critical", "cis": "CIS AWS 1.4", "owasp": "OC2 (Asset Management)",
 "description": "Checks whether the AWS root account has MFA enabled.",
 "risk": "A root account without MFA is one leaked password away from full account compromise.",
 "remediation": "aws iam enable-mfa-device --user-name root --serial-number arn:aws:iam::<acct>:mfa/root --authentication-code1 <code1> --authentication-code2 <code2>"},
{"id": "AWS-IAM-002", "name": "Root account access keys absent", "provider": "aws", "category": "IAM",
 "severity": "critical", "cis": "CIS AWS 1.3", "owasp": "OC2 (Asset Management)",
 "description": "Checks that the root account has no long-lived access keys.",
 "risk": "Root access keys bypass MFA and grant unrestricted control if leaked.",
 "remediation": "Delete root access keys in the IAM console (Security Credentials tab)."},
{"id": "AWS-IAM-003", "name": "IAM password policy min length >= 14", "provider": "aws", "category": "IAM",
 "severity": "high", "cis": "CIS AWS 1.7", "owasp": "OC2 (Asset Management)",
 "description": "Checks the IAM password policy minimum length is at least 14 characters.",
 "risk": "Short passwords are vulnerable to brute-force and cracking attacks.",
 "remediation": "aws iam update-account-password-policy --minimum-password-length 14"},
{"id": "AWS-IAM-004", "name": "IAM password policy requires uppercase", "provider": "aws", "category": "IAM",
 "severity": "medium", "cis": "CIS AWS 1.8", "owasp": "OC2 (Asset Management)",
 "description": "Checks the password policy requires uppercase characters.",
 "risk": "Lower character complexity reduces the effective password strength.",
 "remediation": "aws iam update-account-password-policy --require-uppercase-characters"},
{"id": "AWS-IAM-005", "name": "IAM password policy requires symbols", "provider": "aws", "category": "IAM",
 "severity": "medium", "cis": "CIS AWS 1.11", "owasp": "OC2 (Asset Management)",
 "description": "Checks the password policy requires symbol characters.",
 "risk": "Missing symbol requirement weakens password complexity.",
 "remediation": "aws iam update-account-password-policy --require-symbols"},
{"id": "AWS-IAM-006", "name": "IAM password policy max age <= 90 days", "provider": "aws", "category": "IAM",
 "severity": "medium", "cis": "CIS AWS 1.9", "owasp": "OC2 (Asset Management)",
 "description": "Checks the password policy expires passwords within 90 days.",
 "risk": "Never-expiring passwords increase the window of exposure after a leak.",
 "remediation": "aws iam update-account-password-policy --max-password-age 90"},
{"id": "AWS-IAM-007", "name": "IAM password policy prevents reuse >= 24", "provider": "aws", "category": "IAM",
 "severity": "low", "cis": "CIS AWS 1.10", "owasp": "OC2 (Asset Management)",
 "description": "Checks the password policy prevents reusing the last 24 passwords.",
 "risk": "Password reuse lets attackers replay previously compromised credentials.",
 "remediation": "aws iam update-account-password-policy --password-reuse-prevention 24"},
{"id": "AWS-IAM-008", "name": "MFA enabled for console users", "provider": "aws", "category": "IAM",
 "severity": "high", "cis": "CIS AWS 1.5", "owasp": "OC2 (Asset Management)",
 "description": "Checks that every IAM user with console access has an MFA device.",
 "risk": "Console users without MFA are trivially phished or brute-forced.",
 "remediation": "aws iam create-virtual-mfa-device --virtual-mfa-device-name <user> --outfile <file>.png --bootstrap-method QRCodePNG"},
{"id": "AWS-IAM-009", "name": "No inline policies on users", "provider": "aws", "category": "IAM",
 "severity": "medium", "cis": "CIS AWS 1.15", "owasp": "OC2 (Asset Management)",
 "description": "Checks that IAM users do not carry inline policies (prefer groups/roles).",
 "risk": "Inline policies are hard to audit and tend to accumulate excess privilege.",
 "remediation": "Move inline policies to managed/role policies and delete user inline policies."},
{"id": "AWS-IAM-010", "name": "Access keys rotated within 90 days", "provider": "aws", "category": "IAM",
 "severity": "high", "cis": "CIS AWS 1.13", "owasp": "OC2 (Asset Management)",
 "description": "Checks that active access keys were rotated within the last 90 days.",
 "risk": "Long-lived keys widen the blast radius if they leak.",
 "remediation": "aws iam create-access-key / aws iam delete-access-key --user-name <user> --access-key-id <id>"},

# ---------------- AWS: S3 (5) ----------------
{"id": "AWS-S3-001", "name": "No S3 buckets with public read ACL", "provider": "aws", "category": "Storage",
 "severity": "critical", "cis": "CIS AWS 2.1.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks no S3 bucket grants public READ ACL.",
 "risk": "Public-read buckets can expose sensitive data to anyone on the internet.",
 "remediation": "aws s3api put-bucket-acl --bucket <bucket> --acl private"},
{"id": "AWS-S3-002", "name": "No S3 buckets with public write ACL", "provider": "aws", "category": "Storage",
 "severity": "critical", "cis": "CIS AWS 2.1.2", "owasp": "OC5 (Secure Config)",
 "description": "Checks no S3 bucket grants public WRITE ACL.",
 "risk": "Public-write buckets let attackers plant malicious content or deface data.",
 "remediation": "aws s3api put-bucket-acl --bucket <bucket> --acl private"},
{"id": "AWS-S3-003", "name": "S3 Block Public Access enabled (account)", "provider": "aws", "category": "Storage",
 "severity": "high", "cis": "CIS AWS 2.1.4", "owasp": "OC5 (Secure Config)",
 "description": "Checks that account-level S3 Block Public Access is enabled.",
 "risk": "Without it, a single misconfigured bucket can leak data.",
 "remediation": "aws s3control put-public-access-block --account-id <acct> --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true"},
{"id": "AWS-S3-004", "name": "S3 bucket versioning enabled", "provider": "aws", "category": "Storage",
 "severity": "low", "cis": "CIS AWS 2.1.3", "owasp": "OC9 (Data Protection)",
 "description": "Checks that S3 buckets have versioning enabled.",
 "risk": "Without versioning, accidental or malicious deletions are unrecoverable.",
 "remediation": "aws s3api put-bucket-versioning --bucket <bucket> --versioning-configuration Status=Enabled"},
{"id": "AWS-S3-005", "name": "S3 bucket encryption enabled", "provider": "aws", "category": "Storage",
 "severity": "high", "cis": "CIS AWS 2.1.1 (encryption)", "owasp": "OC9 (Data Protection)",
 "description": "Checks that S3 buckets have server-side encryption configured.",
 "risk": "Unencrypted buckets expose data at rest if accessed via a lower layer.",
 "remediation": "aws s3api put-bucket-encryption --bucket <bucket> --server-side-encryption-configuration '{ \"Rules\": [{\"ApplyServerSideEncryptionByDefault\": {\"SSEAlgorithm\": \"AES256\"}}] }'"},

# ---------------- AWS: CloudTrail (3) ----------------
{"id": "AWS-CT-001", "name": "CloudTrail enabled in all regions", "provider": "aws", "category": "Logging",
 "severity": "high", "cis": "CIS AWS 3.1", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks a multi-region CloudTrail exists.",
 "risk": "Single-region trails miss activity in other regions used for stealth.",
 "remediation": "aws cloudtrail create-trail --name <trail> --s3-bucket-name <bucket> --is-multi-region-trail"},
{"id": "AWS-CT-002", "name": "CloudTrail log file validation enabled", "provider": "aws", "category": "Logging",
 "severity": "medium", "cis": "CIS AWS 3.2", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks CloudTrail log file validation is enabled.",
 "risk": "Without validation, log tampering cannot be detected.",
 "remediation": "aws cloudtrail update-trail --name <trail> --enable-log-file-validation"},
{"id": "AWS-CT-003", "name": "CloudTrail S3 bucket not public", "provider": "aws", "category": "Logging",
 "severity": "critical", "cis": "CIS AWS 3.3", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks the S3 bucket backing CloudTrail is not publicly accessible.",
 "risk": "A public log bucket exposes audit trails to attackers.",
 "remediation": "aws s3api put-bucket-acl --bucket <bucket> --acl private"},

# ---------------- AWS: VPC / Network (4) ----------------
{"id": "AWS-VPC-001", "name": "No SG allows 0.0.0.0/0 on port 22", "provider": "aws", "category": "Network",
 "severity": "high", "cis": "CIS AWS 5.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks no security group allows SSH (22) from 0.0.0.0/0.",
 "risk": "Internet-exposed SSH is a top vector for brute-force and exploit.",
 "remediation": "aws ec2 revoke-security-group-ingress --group-id <sg> --protocol tcp --port 22 --cidr 0.0.0.0/0"},
{"id": "AWS-VPC-002", "name": "No SG allows 0.0.0.0/0 on port 3389", "provider": "aws", "category": "Network",
 "severity": "high", "cis": "CIS AWS 5.2", "owasp": "OC5 (Secure Config)",
 "description": "Checks no security group allows RDP (3389) from 0.0.0.0/0.",
 "risk": "Internet-exposed RDP enables ransomware and credential attacks.",
 "remediation": "aws ec2 revoke-security-group-ingress --group-id <sg> --protocol tcp --port 3389 --cidr 0.0.0.0/0"},
{"id": "AWS-VPC-003", "name": "No SG allows all traffic 0.0.0.0/0", "provider": "aws", "category": "Network",
 "severity": "critical", "cis": "CIS AWS 5.3", "owasp": "OC5 (Secure Config)",
 "description": "Checks no security group allows all protocols/ports from 0.0.0.0/0.",
 "risk": "Fully open security groups expose every service to the internet.",
 "remediation": "aws ec2 revoke-security-group-ingress --group-id <sg> --protocol -1 --cidr 0.0.0.0/0"},
{"id": "AWS-VPC-004", "name": "VPC Flow Logs enabled", "provider": "aws", "category": "Network",
 "severity": "medium", "cis": "CIS AWS 5.4", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks VPC Flow Logs are enabled for network visibility.",
 "risk": "Without flow logs, lateral movement and exfiltration go undetected.",
 "remediation": "aws ec2 create-flow-logs --resource-type VPC --resource-ids <vpc> --traffic-type ALL --log-group-name <lg>"},

# ---------------- AWS: RDS (3) ----------------
{"id": "AWS-RDS-001", "name": "RDS not publicly accessible", "provider": "aws", "category": "Database",
 "severity": "critical", "cis": "CIS AWS 2.3.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks no RDS instance is publicly accessible.",
 "risk": "Public databases are directly reachable by attackers on the internet.",
 "remediation": "aws rds modify-db-instance --db-instance-identifier <id> --no-publicly-accessible"},
{"id": "AWS-RDS-002", "name": "RDS storage encryption enabled", "provider": "aws", "category": "Database",
 "severity": "high", "cis": "CIS AWS 2.3.2", "owasp": "OC9 (Data Protection)",
 "description": "Checks RDS instances have storage encryption enabled.",
 "risk": "Unencrypted databases expose data at rest if the volume leaks.",
 "remediation": "Recreate the instance with --storage-encrypted (encryption is set at creation)."},
{"id": "AWS-RDS-003", "name": "RDS automated backups enabled", "provider": "aws", "category": "Database",
 "severity": "medium", "cis": "CIS AWS 2.3.3", "owasp": "OC9 (Data Protection)",
 "description": "Checks RDS automated backups are enabled (retention > 0).",
 "risk": "Without backups, data loss from corruption or attack is unrecoverable.",
 "remediation": "aws rds modify-db-instance --db-instance-identifier <id> --backup-retention-period 7"},

# ---------------- GCP: IAM (4) ----------------
{"id": "GCP-IAM-001", "name": "No service accounts with admin roles", "provider": "gcp", "category": "IAM",
 "severity": "high", "cis": "CIS GCP 1.1", "owasp": "OC2 (Asset Management)",
 "description": "Checks no service account holds a basic admin/owner role.",
 "risk": "Over-privileged service accounts widen blast radius if a key leaks.",
 "remediation": "gcloud projects remove-iam-policy-binding <proj> --member=<sa> --role=roles/owner"},
{"id": "GCP-IAM-002", "name": "Service account keys not older than 90 days", "provider": "gcp", "category": "IAM",
 "severity": "high", "cis": "CIS GCP 1.2", "owasp": "OC2 (Asset Management)",
 "description": "Checks user-managed service account keys are < 90 days old.",
 "risk": "Stale keys increase exposure if leaked.",
 "remediation": "gcloud iam service-accounts keys delete <key-id> --iam-account=<sa>"},
{"id": "GCP-IAM-003", "name": "Prefer Workload Identity over user keys", "provider": "gcp", "category": "IAM",
 "severity": "medium", "cis": "CIS GCP 1.3", "owasp": "OC2 (Asset Management)",
 "description": "Checks user-managed service account keys are minimized (Workload Identity preferred).",
 "risk": "Long-lived keys are a common leak vector versus short-lived tokens.",
 "remediation": "Migrate workloads to Workload Identity Federation; delete user-managed keys."},
{"id": "GCP-IAM-004", "name": "No primitive roles (Owner/Editor/Viewer)", "provider": "gcp", "category": "IAM",
 "severity": "high", "cis": "CIS GCP 1.4", "owasp": "OC2 (Asset Management)",
 "description": "Checks project IAM bindings use granular roles, not primitive Owner/Editor/Viewer.",
 "risk": "Primitive roles grant far more than needed and violate least privilege.",
 "remediation": "Replace primitive roles with predefined/custom roles via gcloud projects remove/add-iam-policy-binding."},
{"id": "GCP-IAM-005", "name": "No external identities with Owner/Editor", "provider": "gcp", "category": "IAM",
 "severity": "high", "cis": "CIS GCP 1.5", "owasp": "OC2 (Asset Management)",
 "description": "Checks no external (non-org) identities hold Owner/Editor roles on the project.",
 "risk": "External principals with broad roles extend trust beyond your organization boundary.",
 "remediation": "Remove external principals from Owner/Editor bindings via gcloud projects remove-iam-policy-binding."},

# ---------------- GCP: GCS (3) ----------------
{"id": "GCP-GCS-001", "name": "No GCS buckets with allUsers binding", "provider": "gcp", "category": "Storage",
 "severity": "critical", "cis": "CIS GCP 5.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks no GCS bucket IAM binding grants allUsers.",
 "risk": "allUsers makes bucket contents anonymous-readable on the internet.",
 "remediation": "gsutil iam ch -d allUsers:objectViewer gs://<bucket>"},
{"id": "GCP-GCS-002", "name": "No GCS buckets with allAuthenticatedUsers", "provider": "gcp", "category": "Storage",
 "severity": "high", "cis": "CIS GCP 5.2", "owasp": "OC5 (Secure Config)",
 "description": "Checks no GCS bucket grants allAuthenticatedUsers.",
 "risk": "allAuthenticatedUsers exposes data to any logged-in Google account.",
 "remediation": "gsutil iam ch -d allAuthenticatedUsers:objectViewer gs://<bucket>"},
{"id": "GCP-GCS-003", "name": "GCS bucket logging enabled", "provider": "gcp", "category": "Storage",
 "severity": "medium", "cis": "CIS GCP 5.3", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks GCS buckets have access logging / sinks configured.",
 "risk": "Without logging, object access cannot be audited.",
 "remediation": "gsutil logging set on -b gs://<log-bucket> gs://<bucket>"},
{"id": "GCP-GCS-004", "name": "GCS uniform bucket-level access enabled", "provider": "gcp", "category": "Storage",
 "severity": "medium", "cis": "CIS GCP 5.4", "owasp": "OC5 (Secure Config)",
 "description": "Checks GCS buckets use Uniform Bucket-Level Access (UBLA).",
 "risk": "Without UBLA, object-level ACLs can override intended bucket permissions and leak data.",
 "remediation": "gsutil ubla set on gs://<bucket>"},

# ---------------- GCP: Compute (3) ----------------
{"id": "GCP-GCE-001", "name": "Firewall rules no 0.0.0.0/0 on 22", "provider": "gcp", "category": "Network",
 "severity": "high", "cis": "CIS GCP 3.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks no firewall rule allows SSH (22) from 0.0.0.0/0.",
 "risk": "Internet-exposed SSH enables brute-force and exploit attempts.",
 "remediation": "gcloud compute firewall-rules update <rule> --source-ranges=<trusted-cidr>"},
{"id": "GCP-GCE-002", "name": "Firewall rules no 0.0.0.0/0 on 3389", "provider": "gcp", "category": "Network",
 "severity": "high", "cis": "CIS GCP 3.2", "owasp": "OC5 (Secure Config)",
 "description": "Checks no firewall rule allows RDP (3389) from 0.0.0.0/0.",
 "risk": "Internet-exposed RDP enables ransomware and credential attacks.",
 "remediation": "gcloud compute firewall-rules update <rule> --source-ranges=<trusted-cidr>"},
{"id": "GCP-GCE-003", "name": "Instances not using default service account", "provider": "gcp", "category": "Compute",
 "severity": "medium", "cis": "CIS GCP 4.1", "owasp": "OC2 (Asset Management)",
 "description": "Checks compute instances do not use the default service account with full scope.",
 "risk": "The default SA with full access enables privilege escalation if compromised.",
 "remediation": "gcloud compute instances set-service-account --zone=<z> --service-account=<sa> --scopes=<minimal>"},

# ---------------- GCP: Logging (3) ----------------
{"id": "GCP-LOG-001", "name": "Audit logs enabled for all services", "provider": "gcp", "category": "Logging",
 "severity": "high", "cis": "CIS GCP 2.1", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks Audit Logs (Admin Activity + Data Access) are enabled.",
 "risk": "Without audit logs, who-did-what is invisible to defenders.",
 "remediation": "gcloud logging sinks create <sink> --include-children --destination=bigquery.googleapis.com/<ds>"},
{"id": "GCP-LOG-002", "name": "Log metric for IAM changes", "provider": "gcp", "category": "Logging",
 "severity": "medium", "cis": "CIS GCP 2.2", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks a log-based metric/alert exists for IAM policy changes.",
 "risk": "IAM changes without alerting can hide privilege escalation.",
 "remediation": "gcloud logging metrics create iam-changes --description='IAM changes' --log-filter='protoPayload.methodName~\"SetIamPolicy\"'"},
{"id": "GCP-LOG-003", "name": "Log metric for ownership changes", "provider": "gcp", "category": "Logging",
 "severity": "high", "cis": "CIS GCP 2.3", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks a log-based metric/alert exists for project ownership changes.",
 "risk": "Ownership changes without alerting can hide account takeover.",
 "remediation": "gcloud logging metrics create ownership-changes --log-filter='protoPayload.methodName:\"SetIamPolicy\" AND resource.type=\"project\"'"},

# ---------------- GCP: SQL (2) ----------------
{"id": "GCP-SQL-001", "name": "Cloud SQL not publicly exposed", "provider": "gcp", "category": "Database",
 "severity": "critical", "cis": "CIS GCP 6.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks Cloud SQL instances are not publicly exposed (no public IP / authorized networks restricted).",
 "risk": "Publicly exposed databases are directly reachable by attackers.",
 "remediation": "gcloud sql instances patch <inst> --no-assign-ip  (or restrict --authorized-networks)"},
{"id": "GCP-SQL-002", "name": "Cloud SQL requires SSL", "provider": "gcp", "category": "Database",
 "severity": "high", "cis": "CIS GCP 6.2", "owasp": "OC9 (Data Protection)",
 "description": "Checks Cloud SQL requires SSL connections.",
 "risk": "Unencrypted DB connections can be sniffed or MITM'd.",
 "remediation": "gcloud sql instances patch <inst> --require-ssl"},

# ---------------- GCP: Network (3) ----------------
{"id": "GCP-NET-001", "name": "VPC Flow Logs enabled on subnets", "provider": "gcp", "category": "Network",
 "severity": "medium", "cis": "CIS GCP 3.3", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks VPC Flow Logs are enabled on subnets.",
 "risk": "Without flow logs, network traffic cannot be monitored.",
 "remediation": "gcloud compute networks subnets update <subnet> --region=<r> --enable-flow-logs"},
{"id": "GCP-NET-002", "name": "DNS logging enabled on VPC", "provider": "gcp", "category": "Network",
 "severity": "low", "cis": "CIS GCP 3.4", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks Cloud DNS logging is enabled.",
 "risk": "DNS logs help detect exfiltration and reconnaissance.",
 "remediation": "gcloud dns managed-zones update <zone> --enable-logging"},
{"id": "GCP-NET-003", "name": "No legacy networks in use", "provider": "gcp", "category": "Network",
 "severity": "medium", "cis": "CIS GCP 3.5", "owasp": "OC5 (Secure Config)",
 "description": "Checks no legacy (non-subnet) networks are in use.",
 "risk": "Legacy networks lack granular firewall and routing controls.",
 "remediation": "Migrate workloads to VPC (subnet-mode) networks; delete legacy networks."},

# ---------------- Azure: IAM (3) ----------------
{"id": "AZ-IAM-001", "name": "MFA enabled for all users", "provider": "azure", "category": "IAM",
 "severity": "critical", "cis": "CIS Azure 1.1.1", "owasp": "OC2 (Asset Management)",
 "description": "Checks every user has MFA enforced (Conditional Access / per-user).",
 "risk": "Users without MFA are the leading cause of account compromise.",
 "remediation": "Use Conditional Access: New-AzureADMSConditionalAccessPolicy with grantControls includeMfa"},
{"id": "AZ-IAM-002", "name": "No guest users with admin roles", "provider": "azure", "category": "IAM",
 "severity": "high", "cis": "CIS Azure 1.2", "owasp": "OC2 (Asset Management)",
 "description": "Checks no guest (external) users hold admin roles.",
 "risk": "External admins extend trust beyond your organization boundary.",
 "remediation": "Remove guest members from privileged directory roles via Entra ID."},
{"id": "AZ-IAM-003", "name": "Custom subscription owner roles minimized", "provider": "azure", "category": "IAM",
 "severity": "medium", "cis": "CIS Azure 1.3", "owasp": "OC2 (Asset Management)",
 "description": "Checks the number of custom subscription Owner roles is minimized.",
 "risk": "Excess owner roles increase the chance of privilege abuse.",
 "remediation": "Review custom RBAC roles; prefer built-in least-privilege roles."},

# ---------------- Azure: Storage (3) ----------------
{"id": "AZ-STG-001", "name": "No storage accounts with public blob access", "provider": "azure", "category": "Storage",
 "severity": "critical", "cis": "CIS Azure 3.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks no storage account allows public blob access.",
 "risk": "Public blobs expose data anonymously on the internet.",
 "remediation": "(Set-AzStorageAccount -ResourceGroupName <rg> -Name <acct>).Update() after disabling AllowBlobPublicAccess"},
{"id": "AZ-STG-002", "name": "Storage accounts use HTTPS only", "provider": "azure", "category": "Storage",
 "severity": "high", "cis": "CIS Azure 3.2", "owasp": "OC9 (Data Protection)",
 "description": "Checks storage accounts require secure transfer (HTTPS) only.",
 "risk": "HTTP access allows credential/token interception in transit.",
 "remediation": "Set-AzStorageAccount -EnableHttpsTrafficOnly $true"},
{"id": "AZ-STG-003", "name": "Storage account encryption enabled", "provider": "azure", "category": "Storage",
 "severity": "high", "cis": "CIS Azure 3.3", "owasp": "OC9 (Data Protection)",
 "description": "Checks storage accounts have encryption at rest enabled.",
 "risk": "Unencrypted storage exposes data at rest.",
 "remediation": "Encryption is enabled by default; verify via Get-AzStorageAccount | Select Encryption"},

# ---------------- Azure: Network (3) ----------------
{"id": "AZ-NSG-001", "name": "No NSG rules allow port 22 from internet", "provider": "azure", "category": "Network",
 "severity": "high", "cis": "CIS Azure 6.1", "owasp": "OC5 (Secure Config)",
 "description": "Checks no NSG rule allows SSH (22) from Internet (*).",
 "risk": "Internet-exposed SSH enables brute-force and exploit attempts.",
 "remediation": "Update-AzNetworkSecurityRule -Access Deny -SourceAddressPrefix * -DestinationPortRange 22"},
{"id": "AZ-NSG-002", "name": "No NSG rules allow port 3389 from internet", "provider": "azure", "category": "Network",
 "severity": "high", "cis": "CIS Azure 6.2", "owasp": "OC5 (Secure Config)",
 "description": "Checks no NSG rule allows RDP (3389) from Internet (*).",
 "risk": "Internet-exposed RDP enables ransomware and credential attacks.",
 "remediation": "Update-AzNetworkSecurityRule -Access Deny -SourceAddressPrefix * -DestinationPortRange 3389"},
{"id": "AZ-NSG-003", "name": "Network Watcher enabled in all regions", "provider": "azure", "category": "Network",
 "severity": "medium", "cis": "CIS Azure 6.3", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks Network Watcher is enabled in every region with resources.",
 "risk": "Without Network Watcher, NSG flow logs and packet capture are unavailable.",
 "remediation": "New-AzNetworkWatcher -Location <region> -Name <name> -ResourceGroupName <rg>"},

# ---------------- Azure: Monitoring (3) ----------------
{"id": "AZ-MON-001", "name": "Activity log alert for policy assignment", "provider": "azure", "category": "Monitoring",
 "severity": "medium", "cis": "CIS Azure 5.1", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks an activity log alert exists for Policy Assignment changes.",
 "risk": "Undetected policy changes can silently weaken guardrails.",
 "remediation": "Create-AzActivityLogAlert with operationName Microsoft.Authorization/policyAssignments/write"},
{"id": "AZ-MON-002", "name": "Activity log alert for security group changes", "provider": "azure", "category": "Monitoring",
 "severity": "medium", "cis": "CIS Azure 5.2", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks an activity log alert exists for Network Security Group changes.",
 "risk": "NSG changes without alerting can expose resources.",
 "remediation": "Create-AzActivityLogAlert for Microsoft.Network/networkSecurityGroups/write"},
{"id": "AZ-MON-003", "name": "Diagnostic settings enabled on key vault", "provider": "azure", "category": "Monitoring",
 "severity": "medium", "cis": "CIS Azure 5.3", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks Key Vault has diagnostic settings forwarding logs.",
 "risk": "Without diagnostics, secret access cannot be audited.",
 "remediation": "Set-AzDiagnosticSetting -ResourceId <kv> -WorkspaceId <la>"},

# ---------------- Azure: Database (3) ----------------
{"id": "AZ-DB-001", "name": "SQL server auditing enabled", "provider": "azure", "category": "Database",
 "severity": "high", "cis": "CIS Azure 4.1", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks Azure SQL server auditing is enabled.",
 "risk": "Without auditing, DB access and changes are untraceable.",
 "remediation": "Set-AzSqlServerAudit -State Enabled -ResourceGroupName <rg> -ServerName <srv>"},
{"id": "AZ-DB-002", "name": "SQL server TDE enabled", "provider": "azure", "category": "Database",
 "severity": "high", "cis": "CIS Azure 4.2", "owasp": "OC9 (Data Protection)",
 "description": "Checks Transparent Data Encryption is enabled on SQL servers.",
 "risk": "Without TDE, data at rest is exposed if files leak.",
 "remediation": "Enable TDE per database via Set-AzSqlDatabaseTransparentDataEncryption -State Enabled"},
{"id": "AZ-DB-003", "name": "SQL server threat detection enabled", "provider": "azure", "category": "Database",
 "severity": "medium", "cis": "CIS Azure 4.3", "owasp": "OC4 (Logging & Monitoring)",
 "description": "Checks Advanced Threat Protection / Defender for SQL is enabled.",
 "risk": "Without threat detection, SQL injection and anomalous access go unnoticed.",
 "remediation": "Enable Defender for Cloud plan 'SqlServers' or per-server ATP."},
]


CHECK_BY_ID = {c["id"]: c for c in CHECKS}


def checks_for(provider: str) -> list[dict]:
    return [c for c in CHECKS if c["provider"] == provider]


def all_check_ids() -> list[str]:
    return [c["id"] for c in CHECKS]
